name: Update files.json
on:
  push:
    paths:
      - 'images/**'  # 当images文件夹有变化时触发
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: List images
        run: |
          cd images
          ls -1 > ../files.txt
          sed -i 's/^/"/;s/$/"/' ../files.txt
          sed -i '1s/^/[/;$s/$/]/' ../files.txt
          sed -i 's/$/,/' ../files.txt
          sed -i '$s/,$//' ../files.txt
          mv ../files.txt ../files.json
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update files.json"
          file_pattern: "files.json"
